id: IFC4BD3E1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:47:28+00:00'
last_modified: '2022-06-08T11:58:01.346099+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5141
  title: བོ་དོང་པའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    986A:
      image_group_id: I3CN5143
      title: ''
      total_pages: 606
      order: 1
      base_file: 986A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
