id: P009570
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5141
  title: བོ་དོང་པའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    e7458fbef3204228b2d9ac3c2792e790:
      image_group_id: I3CN5143
      title: ''
      volume_number: 1
      total_pages: 606
